
% Rotate as a function of the angle 
function [Rx, Ry, Rz] = Rot( x, y, z ) 

% degree-to-radian conversion 
thetax = x * pi / 180;
thetay = y * pi / 180;
thetaz = z * pi / 180;

        
Rx =  [ 1 0 0 0;...
    0 cos( thetax )  sin( thetax )   0; ...
      0 -sin( thetax )   cos( thetax )   0; ...
            0 0 0 1];
        
        Ry =  [ cos(thetay) 0 -sin(thetay) 0;...
    0 1 0  0; ...
      sin( thetay )  0  cos( thetay )   0; ...
            0 0 0 1];
        
        
Rz = [ cos( thetaz )  -sin( thetaz )   0 0; ...
      sin( thetaz )   cos( thetaz )   0 0; ...
            0           0           1  0;...
            0 0 0 1];
return